#! /bin/bash
for F in "$@"; do
  test -d "$F" && F="$F/scan"
  echo	"## ------------------------------------------------------------"
  echo	"## $F"
  echo	"## ------------------------------------------------------------"
  cat "$F" | grep '+.*\(title\|duration\|Deutsch\|English\)'
done
