#! /bin/bash

test "$1" == "-d" && {
  TODIR=1
  shift
}

for MOVIE in "$@"; do
  test -f "$MOVIE" || {
    echo "SKIP: not exists: $MOVIE" >&2
    continue
  }
  MDIR="$(dirname "$MOVIE")"
  MNAM="$(basename "$MOVIE" .mp4)"

  if [ "$TODIR" ]; then
    test -d "$MDIR/$MNAM" || mkdir "$MDIR/$MNAM"
    mv "$MOVIE" "$MDIR/$MNAM"
    MDIR="$MDIR/$MNAM"
    MOVIE="$MDIR/$MNAM.mp4"
  fi

  if [ ! -e "$MDIR/$MNAM-poster.jpg" ]; then
    mp4art --extract "$MOVIE"
    mv "$MDIR/$MNAM.art[0].jpg" "$MDIR/$MNAM-poster.jpg"
    if [ ! -e "$MDIR/$MNAM-poster.jpg" ]; then
      echo "NO POSTER: $MOVIE" >&2
    elif [ "$TODIR" ]; then
      if [ ! -e "$MDIR/folder.jpg" ]; then
	ln "$MDIR/$MNAM-poster.jpg" "$MDIR/folder.jpg"
      fi
    fi
  fi
done
