#! /bin/bash

function checksums()
{
  for f in VIDEO_TS* VTS_*; do
    head -c 10M $f | md5sum | sed 's/-$/'$f'/'
  done
}

if [ -d "$1" ]; then
  echo "cd '$1'"
  cd "$1"
fi

echo "du -sh ."
checksums	\
| sort	\
| awk '
  {
    if ( $1 != lc )
    {
      lc = $1
      lf = $2
      printf "# %s\n", $0
    }
    else
    {
      printf "ln -f %s %s\n", lf, $2
    }
  }
'
echo "du -sh ."
